---
driver:
  name: dokken
  chef_version: 12.5.1
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  root_path: '/opt/verifier'
  sudo: false
  name: inspec

platforms:
- name: centos-6
  driver:
    image: centos:6

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init

suites:
  - name: dokken_test-12.5.1
    driver:
      chef_version: 12.5.1
    run_list:
    - recipe[test-inspec::default]
